"""fix

Revision ID: 0b53f4841762
Revises: 987c46f42b8a
Create Date: 2025-06-20 15:43:16.230605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b53f4841762'
down_revision: Union[str, None] = '987c46f42b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('brigadier_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('requests_bigadier_id_fkey'), 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'users', ['brigadier_id'], ['id'])
    op.drop_column('requests', 'bigadier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('bigadier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key(op.f('requests_bigadier_id_fkey'), 'requests', 'users', ['bigadier_id'], ['id'])
    op.drop_column('requests', 'brigadier_id')
    # ### end Alembic commands ###
