"""fio to name surname.. nullable changes

Revision ID: 23f70e6b36e7
Revises: d61e23969f83
Create Date: 2025-06-03 18:55:44.160514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f70e6b36e7'
down_revision: Union[str, None] = 'd61e23969f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('surname', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('patronymic', sa.String(), nullable=True))

    conn = op.get_bind()
    conn.execute(
        sa.text("""
            UPDATE users
            SET 
                name = split_part(fio, ' ', 1),
                surname = split_part(fio, ' ', 2),
                patronymic = NULLIF(split_part(fio, ' ', 3), '')
        """)
    )

    op.alter_column('users', 'name', server_default=None)
    op.alter_column('users', 'surname', server_default=None)

    op.drop_column('users', 'fio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fio', sa.VARCHAR(), autoincrement=False, nullable=False, server_default=''))

    conn = op.get_bind()
    conn.execute(
        sa.text("""
            UPDATE users
            SET 
                fio = name || ' ' || surname || ' ' || patronymic
        """)
    )

    op.alter_column('users', 'fio', server_default=None)

    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    op.alter_column('requests', 'contract_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
