"""Add owner_id foreign key to septic

Revision ID: 30bf9bceab79
Revises: 76a162f7f359
Create Date: 2025-05-31 16:17:57.363183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bf9bceab79'
down_revision: Union[str, None] = '76a162f7f359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('septics', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'septics', 'clients', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'septics', type_='foreignkey')
    op.drop_column('septics', 'owner_id')
    # ### end Alembic commands ###
