"""Add requests

Revision ID: 5ff608cb3373
Revises: 573d7e7d7083
Create Date: 2025-06-01 15:18:20.417808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff608cb3373'
down_revision: Union[str, None] = '573d7e7d7083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workmanbrigadiers',
    sa.Column('brigadier_id', sa.Integer(), nullable=False),
    sa.Column('workman_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brigadier_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['workman_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('brigadier_id', 'workman_id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Integer(), nullable=False),
    sa.Column('septic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['septic_id'], ['septics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('workmanbrigadiers')
    # ### end Alembic commands ###
