"""address division

Revision ID: 8a9aab74c130
Revises: f5f725e1ab6f
Create Date: 2025-06-06 17:55:51.608386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9aab74c130'
down_revision: Union[str, None] = 'f5f725e1ab6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('septics', sa.Column('city', sa.String(), server_default='', nullable=False))
    op.add_column('septics', sa.Column('street', sa.String(), server_default='', nullable=False))
    op.add_column('septics', sa.Column('house', sa.String(), server_default='', nullable=False))


    op.alter_column('septics', 'city', server_default=None)
    op.alter_column('septics', 'street', server_default=None)
    op.alter_column('septics', 'house', server_default=None)

    op.drop_column('septics', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('septics', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('septics', 'house')
    op.drop_column('septics', 'street')
    op.drop_column('septics', 'city')
    # ### end Alembic commands ###
