"""added brigadier id to request

Revision ID: 987c46f42b8a
Revises: e69a49611cd9
Create Date: 2025-06-20 15:10:58.370199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987c46f42b8a'
down_revision: Union[str, None] = 'e69a49611cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('bigadier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'users', ['bigadier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'bigadier_id')
    # ### end Alembic commands ###
