"""some models changes to deal with requests

Revision ID: cb2dfc012dd2
Revises: 883213ced7e2
Create Date: 2025-06-07 18:58:48.592738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb2dfc012dd2'
down_revision: Union[str, None] = '883213ced7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('planed_start_time', sa.Time(), nullable=False))
    op.add_column('requests', sa.Column('planed_start_date', sa.Date(), nullable=False))
    op.add_column('requests', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('requestservices', 'planed_start_date')
    op.drop_column('requestservices', 'planed_start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestservices', sa.Column('planed_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('requestservices', sa.Column('planed_start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('requests', 'comment')
    op.drop_column('requests', 'planed_start_date')
    op.drop_column('requests', 'planed_start_time')
    # ### end Alembic commands ###
