"""add link to request-services another

Revision ID: e69a49611cd9
Revises: 74ea06eeedff
Create Date: 2025-06-08 16:14:56.219411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69a49611cd9'
down_revision: Union[str, None] = '74ea06eeedff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestservices', sa.Column('request_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'requestservices', 'requests', ['request_id'], ['id'])
    op.drop_column('requestservices', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestservices', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'requestservices', type_='foreignkey')
    op.drop_column('requestservices', 'request_id')
    # ### end Alembic commands ###
